name: etokan-lib

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 	NODE_AUTH_TOKEN
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install
    
    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

    - name: add npm user
      run: npm adduser
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish 
      run: npm publish
      working-directory: dist/etokan-lib
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
